### ISSUE TITLE
Cannot run `command` with roomba 9-series

### ISSUE THREAD

**Issue by VictorKoenders** [cecton/roomba#9]
Running `cargo run -- command` doesn't seem to work on my roomba
It returns `Error: PahoDescr(1, "CONNACK return code")`

My `~/.config/roomba.toml` is:
```toml
hostname = '192.168.1.101'
username = '<username>'
password = '<password>'
```
